import { ToolDefinition } from "../types";

export const SUPPORTED_TOOLS: ToolDefinition[] = [
  {
    id: "claude",
    name: "Claude Code",
    command: "claude",
    protocol: "anthropic",
    description: "Anthropic Claude Code Terminal Agent",
    configFile: "~/.claude/settings.json",
    color: "#D97706",
    icon: "🟧",
    defaultModel: "claude-fable-5",
  },
  {
    id: "codex",
    name: "OpenAI Codex CLI / App",
    command: "codex",
    protocol: "openai",
    description: "OpenAI Codex CLI (config.toml & auth.json)",
    configFile: "~/.codex/config.toml",
    color: "#2563EB",
    icon: "🟦",
    defaultModel: "req/gpt-5.6-sol",
  },
  {
    id: "openclaw",
    name: "OpenClaw",
    command: "openclaw",
    protocol: "anthropic",
    description: "Open-source Claude Code alternative",
    configFile: "~/.openclaw/config.json",
    color: "#EA580C",
    icon: "🐾",
    defaultModel: "claude-fable-5",
  },
  {
    id: "deepseek-tui",
    name: "DeepSeek TUI",
    command: "deepseek",
    protocol: "openai",
    description: "DeepSeek Terminal Coding Agent (Rust TUI)",
    configFile: "~/.deepseek/config.toml",
    color: "#4D6BFE",
    icon: "🔵",
    defaultModel: "deepseek-v4-flash",
  },
  {
    id: "qwen",
    name: "Qwen Code",
    command: "qwen",
    protocol: "openai",
    description: "Alibaba Qwen Code CLI Agent",
    configFile: "~/.qwen/settings.json",
    color: "#7C3AED",
    icon: "🟣",
    defaultModel: "stali/qwen3-codex",
  },
  {
    id: "opencode",
    name: "OpenCode",
    command: "opencode",
    protocol: "openai",
    description: "OpenCode AI Terminal Coding Tool",
    configFile: "~/.opencode/config.json",
    color: "#059669",
    icon: "🟢",
    defaultModel: "gpt-5.6-sol",
  },
  {
    id: "kilo",
    name: "Kilo Code",
    command: "kilo",
    protocol: "openai",
    description: "Kilo Code Fast Terminal Coding Assistant",
    configFile: "~/.kilo/config.json",
    color: "#DC2626",
    icon: "⚡",
    defaultModel: "claude-fable-5",
  },
  {
    id: "droid",
    name: "Droid CLI",
    command: "droid",
    protocol: "openai",
    description: "Factory Droid Autonomous Coding Agent",
    configFile: "~/.droid/config.json",
    color: "#0284C7",
    icon: "🤖",
    defaultModel: "claude-fable-5",
  },
  {
    id: "cline",
    name: "Cline (VS Code)",
    command: "code",
    protocol: "anthropic",
    description: "Autonomous coding agent in VS Code",
    configFile: "~/.vscode/cline_settings.json",
    color: "#16A34A",
    icon: "🧩",
    defaultModel: "claude-fable-5",
  },
  {
    id: "roo",
    name: "Roo Code (VS Code)",
    command: "code",
    protocol: "anthropic",
    description: "Community AI agent for VS Code",
    configFile: "~/.vscode/roo_settings.json",
    color: "#9333EA",
    icon: "🦘",
    defaultModel: "claude-fable-5",
  },
  {
    id: "grok-build",
    name: "Grok Build",
    command: "grok",
    protocol: "openai",
    description: "xAI Grok Build TUI coding agent",
    configFile: "~/.grok/config.toml",
    color: "#1DA1F2",
    icon: "⚡",
    defaultModel: "grok-4.6",
  },
  {
    id: "cowork",
    name: "Cowork",
    command: "cowork",
    protocol: "openai",
    description: "AI Cowork terminal workflow agent",
    configFile: "~/.cowork/settings.json",
    color: "#0D9488",
    icon: "👥",
    defaultModel: "gpt-5.6-sol",
  },
  {
    id: "jcode",
    name: "jcode",
    command: "jcode",
    protocol: "openai",
    description: "High-performance Rust coding agent (14ms boot)",
    configFile: "~/.jcode/config.toml",
    color: "#FF6B35",
    icon: "🦀",
    defaultModel: "claude-opus-5",
  },
];
